sudo: false
language: python
python: "3.4"
env:
  matrix:
    - TESTENV=linters
    - TESTENV=py27
    - TESTENV=py27-xdist
    - TESTENV=py27-pytest-latest
    - TESTENV=py34
    - TESTENV=coveralls
install:
  - pip install tox
# mysql_install_db will not work if it can't find the my-default.cnf file
before_script: sudo cp /etc/mysql/my.cnf /usr/share/mysql/my-default.cnf
script: tox -e $TESTENV
branches:
  except:
    - /^\d/
notifications:
  email:
  - bubenkoff@gmail.com
