language: python
before_install:
  # - apt-get install libmemcached-dev libmysqlclient-dev
# command to install dependencies
install:
  - pip install python-coveralls virtualenv
# # command to run tests
script: python setup.py test
after_success:
  - pip install -r requirements-testing.txt -e .
  - py.test --cov=pytest_services --cov-report=term-missing tests
  - coveralls
branches:
  except:
    - /^\d/
notifications:
    email:
        - bubenkoff@paylogic.com
